# Generated by Django 2.2.1 on 2019-06-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id_organism', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.BooleanField(default=True)),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('isolated', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('seq_date', models.DateField(blank=True, default=None, null=True)),
                ('gen_size', models.FloatField(blank=True, default=None, null=True)),
                ('gen_contamination', models.FloatField(blank=True, default=None, null=True)),
                ('gen_completeness', models.FloatField(blank=True, default=None, null=True)),
                ('gc_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('n_orfs', models.IntegerField(blank=True, default=None, null=True)),
                ('temp_associated', models.FloatField(blank=True, default=None, null=True)),
                ('temp_min', models.FloatField(blank=True, default=None, null=True)),
                ('temp_max', models.FloatField(blank=True, default=None, null=True)),
                ('ph_associated', models.FloatField(blank=True, default=None, null=True)),
                ('ph_min', models.FloatField(blank=True, default=None, null=True)),
                ('ph_max', models.FloatField(blank=True, default=None, null=True)),
                ('access_src', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('access_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('biosample', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('bioproject', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ftp_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('annotation', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Confidence',
            fields=[
                ('organism', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='acidb.Organism')),
                ('ph', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('temp', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Confidence',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_src', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tax_id', models.IntegerField(blank=True, default=None, null=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phylum', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tax_class', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('order', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('family', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('genus', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('species', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
            options={
                'verbose_name_plural': 'Taxonomy',
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_text', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
        ),
    ]
