# Generated by Django 2.2.1 on 2019-05-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id_organism', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('isolated', models.CharField(default=None, max_length=50)),
                ('state', models.CharField(default=None, max_length=50)),
                ('seq_date', models.DateField(default=None)),
                ('gen_size', models.FloatField(default=None)),
                ('gen_contamination', models.FloatField(default=None)),
                ('ge_completeness', models.FloatField(default=None)),
                ('gc_percentage', models.FloatField(default=None)),
                ('n_orfs', models.IntegerField(default=None)),
                ('temp_associeted', models.FloatField(default=None)),
                ('temp_min', models.FloatField(default=None)),
                ('temp_max', models.FloatField(default=None)),
                ('ph_associeted', models.FloatField(default=None)),
                ('ph_min', models.FloatField(default=None)),
                ('ph_max', models.FloatField(default=None)),
                ('access_src', models.CharField(default=None, max_length=50)),
                ('access_id', models.CharField(default=None, max_length=50)),
                ('biosample', models.CharField(default=None, max_length=50)),
                ('bioproject', models.CharField(default=None, max_length=50)),
                ('ftp_url', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_src', models.CharField(default=None, max_length=20)),
                ('tax_id', models.IntegerField(default=None)),
                ('domain', models.CharField(default=None, max_length=50)),
                ('phylum', models.CharField(default=None, max_length=50)),
                ('classorder', models.CharField(default=None, max_length=50)),
                ('family', models.CharField(default=None, max_length=50)),
                ('genus', models.CharField(default=None, max_length=50)),
                ('species', models.CharField(default=None, max_length=50)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_name', models.CharField(default=None, max_length=50)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_text', models.CharField(default=None, max_length=100)),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
        ),
    ]
