# Generated by Django 2.2.1 on 2019-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='access_id',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='access_src',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='bioproject',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biosample',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ftp_url',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gc_percentage',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ge_completeness',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_contamination',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_size',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='isolated',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='n_orfs',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_associeted',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_max',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_min',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='seq_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_associeted',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_max',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_min',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
