# Generated by Django 2.2.1 on 2019-10-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('nr_id', models.AutoField(primary_key=True, serialize=False)),
                ('prot_len', models.IntegerField(blank=True, default=None, null=True)),
                ('isoelectric_p', models.FloatField(blank=True, default=None, null=True)),
                ('mol_weight', models.FloatField(blank=True, default=None, null=True)),
                ('tmhmm', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('hmmtop', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('psort', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('pfam', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('signal_p', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('cog', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('cog_category', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proteome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prot_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Protein')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Organism')),
            ],
            options={
                'verbose_name_plural': 'Proteome',
            },
        ),
        migrations.CreateModel(
            name='Kegg_ko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegg_ko', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Inter_fam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_fam', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('nr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Protein')),
            ],
        ),
        migrations.CreateModel(
            name='Ec_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('nr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acidb.Protein')),
            ],
        ),
    ]
