# Generated by Django 2.2.1 on 2019-07-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0002_auto_20190710_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthdetail',
            old_name='ph',
            new_name='ph_confidence',
        ),
        migrations.RenameField(
            model_name='growthdetail',
            old_name='temp',
            new_name='temp_confidence',
        ),
    ]
