# Generated by Django 2.2.1 on 2019-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0003_auto_20190710_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthdetail',
            name='ph_src',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='growthdetail',
            name='temp_src',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ftp_url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
