# Generated by Django 2.2.1 on 2019-05-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0004_auto_20190528_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organism',
            old_name='ph_associeted',
            new_name='ph_associated',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='temp_associeted',
            new_name='temp_associated',
        ),
    ]
