# Generated by Django 2.2.1 on 2019-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0004_auto_20190710_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='isolated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
