# Generated by Django 2.2.1 on 2019-08-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0005_auto_20190806_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strain',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='acidb.Organism'),
        ),
    ]
