# Generated by Django 2.2.1 on 2019-05-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0005_auto_20190528_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='ftp_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
