# Generated by Django 2.2.1 on 2019-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0006_auto_20190528_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='access_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='access_src',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='bioproject',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='biosample',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ftp_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gc_percentage',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_completeness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_contamination',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='gen_size',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='isolated',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='n_orfs',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_associated',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_max',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='ph_min',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='seq_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='state',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_associated',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_max',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='temp_min',
            field=models.FloatField(default=None, null=True),
        ),
    ]
