# Generated by Django 2.2.1 on 2019-08-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acidb', '0007_auto_20190807_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='acidb.Organism'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='acidb.Organism'),
        ),
    ]
